### ISSUE TITLE
Cannot update to required Java version ?

### ISSUE THREAD

**Issue by stonemull** [TMaxElectronics/Gerber2Chitubox#1]
Really keen to try this but I cannot get your jar file running with the latest (windows) version of the java runtime. Not sure how to proceed.

PS C:\Program Files\Java\jre1.8.0_321\bin> java -jar C:\temp\G2C.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: g2c/application/Main has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:59)
PS C:\Program Files\Java\jre1.8.0_321\bin>

btw, Method I want to try is using the resin as the resist, remove the vat and add/print/create a smaller vat with just a thin resin layer and deposit the resin directly onto the pcb copper.

**Comment by TMaxElectronics** [comment]
Hey there, I have compiled the jar with the latest JDK, which is a newer version than what is available as a free jre I beleive. I'll recompile for 1.8 and publish the jar, then it should run again. Alternatively you could also install a current openjdk version that should be able to run it too.

**Comment by stonemull** [comment]
Hey cheers for the reply, I just dropped by to say I installed JDK into visual studio code earlier and could then run the java anyway.
I think I'm using it correctly, but I'm using kicad gerbers and they don't seem to work with the gerber rendering engine. I also tried just the standalone gerber project you used and I just get a basic filled in solid board shape with no tracks.
I just used some of my existing gerbers so I'll do a few more experiments later with simpler shapes and see if I can make any sense of it.
Thanks for the project though, I would love to help you complete it if you have a chance but my software skills are meagre, so I'm more of a feedback kind of guy :)
C on embedded controllers is my little niche.

**Comment by TMaxElectronics** [comment]
Hmm that is interesting. I've had some issues with the ones exported by altium aswell and modified the Gerber Library accordingly. Can you maybe attach some of the gerber files that cause problems here? :)

In my opinion C is acutally similar enough to java to make code at the very least understandable. I come from the same background and the little bit of Java I know all came from modifying other peoples code :D

**Comment by stonemull** [comment]
Well here is the specific one I tried, it was small enough that I thought it would fit on the display and I already had it ready to go, that's the only reason I chose it.

this is what gerbview reckons it looks like and the the zip has just the front copper gerber

![gerbview](https://user-images.githubusercontent.com/6361365/159385918-00a793f9-a6bf-4b5e-9060-ba606b3a5c8e.PNG)

[DIN_mount.zip](https://github.com/TMaxElectronics/Gerber2Chitubox/files/8322472/DIN_mount.zip)

**Comment by TMaxElectronics** [comment]
Thanks I'll give it a try when I have the time. I suspect it might get confused by the ground plane polygon. Have you maybe tried it without that? Oh and would you mind opening another issue for this? That would make them easier to track 😃

**Comment by Pitichinaccio** [comment]
Hi! Thanks for sharing this great project.
Unfortunatey I have a similar issue. I can't run the G2C.jar with the runtime enviroment from Oracle (same error message as stonemull posted above) so I tried it with the latest version from OpenJDK (18.0.1).
The jar-file is running now, but I can't open a Gerber-file. The drop-down-menu "FILE" doesn't work and If I try to add a file using the +-button (if that is the right way?), nothing happens. I am using EAGLE for generating the Gerbers. Maybe there is something wrong with them?

**Comment by GigaTech** [comment]
Hi, I get the same error.

```
C:\Program Files\Java\jre1.8.0_333>java -jar R:\_PCB\_Software\Gerber2Chitubox\Gerber2Chitubox-main\G2C.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: g2c/application/Main has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:59)
```
downloaded `G2C.jar` today

hoping I can get this working with elegoo saturn
